// "use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono, Mulish, Quicksand } from "next/font/google";
import "./globals.css";
import "./style.css";
import Header from "./component/Header";
import Footer from "./component/footer";
import WhatsAppButton from "./component/WhatsAppButton";
import ChatBotWidget from "./component/ChatBotWidget";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const quicksand =  Quicksand({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
})

const muli = Mulish({
  subsets: ["latin"],
  display: "swap",
  weight: ["200", "400", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  metadataBase: new URL(
    "https://vrajdentalclinic.com"
  ),

  title: "Dental Clinic",
  description: "Generated by Dental Clinic",
};

const schemaData = {
  "@context": "https://schema.org",

  "@type": "Dentist",

  name: "Vraj Group of Dental Clinic",

  image:
    "https://vrajdentalclinic.com/front/images/logo_n.png",

  "@id":
    "https://www.google.com/maps/place//data=!4m2!3m1!1s0x395fcfc90fd724c1:0x8b86ff2a5fbd0af9?source=g.page.m",

  url: "https://vrajdentalclinic.com",

  telephone: "9427784433",

  address: {
    "@type": "PostalAddress",

    streetAddress:
      "21/FF divya plaza complex, above Jigar provision store, ajwa kamlanagar road",

    addressLocality: "Vadodara",

    postalCode: "390019",

    addressCountry: "IN",
  },

  geo: {
    "@type": "GeoCoordinates",

    latitude: 22.3192932,

    longitude: 73.2500087,
  },

  openingHoursSpecification: [
    {
      "@type":
        "OpeningHoursSpecification",

      dayOfWeek: [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
      ],

      opens: "10:00",

      closes: "13:00",
    },

    {
      "@type":
        "OpeningHoursSpecification",

      dayOfWeek: [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
      ],

      opens: "16:00",

      closes: "20:30",
    },
  ],

  sameAs: [
    "https://www.facebook.com/vrajgroupofdental/",
    "https://twitter.com/drujasshah",
    "https://www.instagram.com/vrajgroupofdental/",
    "https://www.youtube.com/channel/UCXOSLaCRaKMd43AhX2bCDQA",
    "https://www.linkedin.com/in/dr-ujas-shah-0342b31b9/",
    "https://ujasshah.tumblr.com",
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Preconnects help fonts load faster */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        {/* These match the @import URLs in globals.css; keeping both is fine, or remove @import lines above if you prefer only link tags */}
        <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Muli:200,300,400,500,600,700,800,900&display=swap" rel="stylesheet" />

        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(schemaData),
          }}
        />

        {/* Google Analytics */}
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-F5JQGYBRFS"
          strategy="afterInteractive"
        />

        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];

            function gtag(){
              dataLayer.push(arguments);
            }

            gtag('js', new Date());

            gtag('config', 'G-F5JQGYBRFS');
          `}
        </Script>
      </head>
      <body
        className={`${quicksand.className} ${muli.className}`}
      >
        <Header />
        {children}
        <ChatBotWidget />
        <WhatsAppButton />
        <Footer />
      </body>
    </html>
  );
}
