// "use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono, Mulish, Quicksand } from "next/font/google";
import "./globals.css";
import "./style.css";
import Header from "./component/Header";
import Footer from "./component/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const quicksand =  Quicksand({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
})

const muli = Mulish({
  subsets: ["latin"],
  display: "swap",
  weight: ["200", "400", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Dental Clinic",
  description: "Generated by Dental Clinic",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Preconnects help fonts load faster */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        {/* These match the @import URLs in globals.css; keeping both is fine, or remove @import lines above if you prefer only link tags */}
        <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Muli:200,300,400,500,600,700,800,900&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${quicksand.className} ${muli.className}`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
